# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_task_assigned_from_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
