# Generated by Django 5.1.4 on 2026-06-01 14:12

from django.db import migrations


def set_done_for_completed(apps, schema_editor):
    Task = apps.get_model('transcriptions', 'Task')
    Task.objects.filter(is_completed=True).update(status='done')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0007_task_status_tasknote'),
    ]

    operations = [
        migrations.RunPython(set_done_for_completed, reverse_noop),
    ]
