# Generated by Django 5.1.4 on 2026-06-02 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0008_backfill_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('senior_team_leader', 'Senior Team Leader'), ('junior_team_leader', 'Junior Team Leader'), ('employee', 'Employee'), ('outsource_staff', 'OutSource Staff')], default='employee', max_length=32)),
                ('requested_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('senior_team_leader', 'Senior Team Leader'), ('junior_team_leader', 'Junior Team Leader'), ('employee', 'Employee'), ('outsource_staff', 'OutSource Staff')], default='employee', max_length=32)),
                ('requested_manager_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('permanently_rejected', 'Permanently rejected')], default='pending', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
