# Generated by Django 5.1.4 on 2026-06-02 18:54

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('transcriptions', 'UserProfile')
    for user in User.objects.all():
        if UserProfile.objects.filter(user=user).exists():
            continue
        role = 'admin' if user.is_superuser else 'employee'
        UserProfile.objects.create(
            user=user,
            role=role,
            requested_role=role,
            status='active',
        )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0009_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, reverse_noop),
    ]
