# Generated by Django 5.1.4 on 2026-06-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0010_backfill_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('delivered', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done')], default='delivered', max_length=16),
        ),
    ]
